Antes disso, a 'Query1' tem que ser criada. Basta criar uma query vazia no power query e digitar "= List.dates".
Após configurar com a data de início, a quantidade de dias a partir do início e o espaçamento dos dias (1),
basta abrir o 'Advanced Editor' e colar o código abaixo.
Para mudar o range da data, basta editar a primeira etapa "Source"
let
    Source = Query1(#date(2016, 1, 1), 1096, #duration(1, 0, 0, 0)),
    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type date}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Data"}}),
    #"Inserted Year" = Table.AddColumn(#"Renamed Columns", "Year", each Date.Year([Data]), Int64.Type),
    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Data]), Int64.Type),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([Data]), type text),
    #"Capitalized Each Word" = Table.TransformColumns(#"Inserted Month Name",{{"Month Name", Text.Proper, type text}}),
    #"Inserted Week of Month" = Table.AddColumn(#"Capitalized Each Word", "Week of Month", each Date.WeekOfMonth([Data]), Int64.Type),
    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Week of Month", "Week of Year", each Date.WeekOfYear([Data]), Int64.Type),
    #"Added Custom Column" = Table.AddColumn(#"Inserted Week of Year", "Custom", each Text.Combine({Text.From([Year], "pt-BR"), "/", Text.Start(Text.Lower([Month Name]), 3)}), type text),
    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom Column",{{"Custom", "Ano/Mes"}, {"Week of Year", "Semana do Ano"}, {"Week of Month", "Semana do Mes"}, {"Month Name", "Nome Mes"}, {"Month", "Mes"}, {"Year", "Ano"}}),
    #"Inserted Day" = Table.AddColumn(#"Renamed Columns1", "Day", each Date.Day([Data]), Int64.Type),
    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Day",{{"Day", "Dia do Mes"}}),
    #"Inserted Day of Week" = Table.AddColumn(#"Renamed Columns2", "Day of Week", each Date.DayOfWeek([Data]), Int64.Type),
    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Day of Week",{{"Day of Week", "Dia da Semana"}}),
    #"Inserted Day of Year" = Table.AddColumn(#"Renamed Columns3", "Day of Year", each Date.DayOfYear([Data]), Int64.Type),
    #"Renamed Columns4" = Table.RenameColumns(#"Inserted Day of Year",{{"Day of Year", "Dia do Ano"}}),
    #"Inserted Quarter" = Table.AddColumn(#"Renamed Columns4", "Quarter", each Date.QuarterOfYear([Data]), Int64.Type),
    #"Renamed Columns5" = Table.RenameColumns(#"Inserted Quarter",{{"Quarter", "Trimestre"}}),
    #"Added Conditional Column" = Table.AddColumn(#"Renamed Columns5", "Custom", each if [Trimestre] = 1 then "1º Trimestre" else if [Trimestre] = 2 then "2º Trimestre" else if [Trimestre] = 3 then "3º Trimestre" else "4º Trimestre"),
    #"Renamed Columns6" = Table.RenameColumns(#"Added Conditional Column",{{"Custom", "Nome do Trimestre"}}),
    #"Added Conditional Column1" = Table.AddColumn(#"Renamed Columns6", "Custom", each if [Trimestre] = 1 then 1 else if [Trimestre] = 2 then 1 else if [Trimestre] = 3 then 2 else 2),
    #"Renamed Columns7" = Table.RenameColumns(#"Added Conditional Column1",{{"Custom", "Semestre"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns7",{{"Nome do Trimestre", type text}, {"Semestre", Int64.Type}}),
    #"Added Conditional Column2" = Table.AddColumn(#"Changed Type1", "Custom", each if [Semestre] = 1 then "1º Semestre" else "2º Semestre"),
    #"Renamed Columns8" = Table.RenameColumns(#"Added Conditional Column2",{{"Custom", "Nome do Semestre"}}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns8",{{"Nome do Semestre", type text}})
in
    #"Changed Type2"