# -*- coding: utf-8 -*-
"""Atividades_dataframe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IDX3_tScwxwAqPWIeK3RPFTBgwpF73Sa
"""

import pandas as pd
from google import colab as cl

file_upload = cl.files.upload()

df = pd.read_csv('train.csv')
df.head()

# 1. Qual o valor da informação armazenada na linha 30 e na coluna 10?
df.iloc[30, 10]

# 2. Selecione as linhas 0 a 20 e as colunas 0 a 2
df.iloc[0:21,0:3]

# 3. Selecione as linhas 5 até 30 e somente a coluna 'Delvery_person_Age'
df.loc[5:30,['Delivery_person_Age']]

# 4. Selecione as linhas 40 a 42 e as seguintes colunas: “Restaurant_latitude”,“Restaurant_longitude”, "Delivery_location_latitude”,“Delivery_location_longitude”
df.loc[40:42,['Restaurant_latitude','Restaurant_longitude','Delivery_location_latitude','Delivery_location_longitude']]

# 5. Qual a menor data de entrega da coluna “Order_Date” entre as linhas 0 a 50?
aux = df.loc[:50,['Order_Date']]
aux.min()

# 6. Qual a menor data de entrega da coluna “ Time_Orderd ” entre as linhas 0 a 50?
aux = df.loc[:50,['Time_Orderd']]
aux.min()

# 7. Quais os nomes únicos da coluna “City” entre as linhas 50 e 70?
df.loc[50:70,'City'].unique().tolist()

# 8. Quais os nomes únicos da coluna “Weatherconditions” entre as linhas 0 e 10?
df.loc[:10,'Weatherconditions'].unique().tolist()

# 9. Quais os tipos de densidade de trânsito presente na coluna “Road_traffic_density ” entre as linhas 0 a 20?
df.loc[:20,'Road_traffic_density'].unique().tolist()

# 10. Qual o ID do entregador de comida mais velho entre as colunas 50 e 70?
aux = df.loc[50:70,['Delivery_person_Age']]
aux.max()

# 11. Qual o ID do entregador de comida com a melhor avaliação de entrega entre as colunas 50 e 70?
df1 = df.loc[50:70,['ID','Delivery_person_Ratings']]
df1.loc[df1['Delivery_person_Ratings'].idxmax(),'ID']

# 12. Quais os tipos de veículos utilizados pelos entregadores entre as linhas 0 a 30?
df.loc[:30,'Type_of_vehicle'].unique().tolist()

# 13. Quais os tipos de pedidos único que foram entregues entre as colunas 100 e 120?
df.loc[100:120,'Type_of_order'].unique().tolist()