# -*- coding: utf-8 -*-
"""Atividades_dataframe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19zHu1-AjW0bdvaKSSn1fInzIpaEt-hZW

# Imports e file upload
"""

import pandas as pd
from google import colab as cl

file_upload = cl.files.upload()

"""# Read"""

df = pd.read_csv('train.csv')
df.head()

"""# Limpeza de dados"""

# Limpeza dos dados para melhorar o uso da base de dados
# Conversão da coluna Delivery_person_Age de string para int
df['Delivery_person_Age'] = pd.to_numeric(df['Delivery_person_Age'],errors='coerce') # Converte a coluna 'delivery_person_age' para float e coloca 'NaN' para qualquer valor diferente de número
df.dropna(subset=['Delivery_person_Age'],inplace=True) # Remove as linhas que tiver 'NaN'
df['Delivery_person_Age'] = df['Delivery_person_Age'].astype('int8') # Transforma o tipo de float para int8
# print(df['Delivery_person_Age'].dtypes)

# Conversão da coluna Delivery_person_Ratings de string para float
df['Delivery_person_Ratings'] = pd.to_numeric(df['Delivery_person_Ratings'],errors='coerce') # Converte a coluna 'delivery_person_ratings' para float e coloca 'NaN' para qualquer valor diferente de número
df.dropna(subset=['Delivery_person_Ratings'],inplace=True) # Remove as linhas que tiver 'NaN'
df['Delivery_person_Ratings'] = df['Delivery_person_Ratings'].astype('float16') # Transforma o tipo de float para float16
# print(df['Delivery_person_Ratings'].dtypes)

# Conversão da coluna Order_Date de string para datetime
df['Order_Date'] = pd.to_datetime(df['Order_Date'],format='%d-%m-%Y')
# print(df['Order_Date'])

# Conversão da coluna multiple_deliveries de string para int
df['multiple_deliveries'] = pd.to_numeric(df['multiple_deliveries'],errors = 'coerce') # Converte a coluna 'multiple_deliveries' para float e coloca 'NaN' para qualquer valor diferente de número
df.dropna(subset=['multiple_deliveries'], inplace=True) # Remove as linhas que tiver 'NaN'
df['multiple_deliveries'] = df['multiple_deliveries'].astype('int8') # Transforma de float para int8
# print(df['multiple_deliveries'].dtypes)

# Remover espaços em branco no final das strings de algumas colunas
df['ID'] = df['ID'].str.strip()
df['Road_traffic_density'] = df['Road_traffic_density'].str.strip()
df['Type_of_order'] = df['Type_of_order'].str.strip()
df['Type_of_vehicle'] = df['Type_of_vehicle'].str.strip()
df['City'] = df['City'].str.strip()
df['Festival'] = df['Festival'].str.strip()

"""# Primera Atividade

"""

# Primeiras ativdades de dataframe
# 1. Qual o valor da informação armazenada na linha 30 e na coluna 10?
df.iloc[30, 10]

# 2. Selecione as linhas 0 a 20 e as colunas 0 a 2
df.iloc[0:21,0:3]

# 3. Selecione as linhas 5 até 30 e somente a coluna 'Delvery_person_Age'
df.loc[5:30,['Delivery_person_Age']]

# 4. Selecione as linhas 40 a 42 e as seguintes colunas: “Restaurant_latitude”,“Restaurant_longitude”, "Delivery_location_latitude”,“Delivery_location_longitude”
df.loc[40:42,['Restaurant_latitude','Restaurant_longitude','Delivery_location_latitude','Delivery_location_longitude']]

# 5. Qual a menor data de entrega da coluna “Order_Date” entre as linhas 0 a 50?
aux = df.loc[:50,['Order_Date']]
aux.min()

# 6. Qual a menor data de entrega da coluna “ Time_Orderd ” entre as linhas 0 a 50?
aux = df.loc[:50,['Time_Orderd']]
aux.min()

# 7. Quais os nomes únicos da coluna “City” entre as linhas 50 e 70?
df.loc[50:70,'City'].unique().tolist()

# 8. Quais os nomes únicos da coluna “Weatherconditions” entre as linhas 0 e 10?
df.loc[:10,'Weatherconditions'].unique().tolist()

# 9. Quais os tipos de densidade de trânsito presente na coluna “Road_traffic_density ” entre as linhas 0 a 20?
df.loc[:20,'Road_traffic_density'].unique().tolist()

# 10. Qual o ID do entregador de comida mais velho entre as colunas 50 e 70?
aux = df.loc[50:70,['Delivery_person_Age']]
aux.max()

# 11. Qual o ID do entregador de comida com a melhor avaliação de entrega entre as colunas 50 e 70?
df1 = df.loc[50:70,['ID','Delivery_person_Ratings']]
df1.loc[df1['Delivery_person_Ratings'].idxmax(),'ID']

# 12. Quais os tipos de veículos utilizados pelos entregadores entre as linhas 0 a 30?
print(df.loc[:30,'Type_of_vehicle'].unique().tolist())

# 13. Quais os tipos de pedidos único que foram entregues entre as colunas 100 e 120?
df.loc[100:120,'Type_of_order'].unique().tolist()

"""# Segunda Atividade"""

# Mais atividades do uso de dataframes
# 1. Qual o número total de entregadores cadastrados na base de dados?
# delivery_people_count = df['Delivery_person_ID'].count()
# print(delivery_people_count)

# 2. Qual o número total de entregadores únicos cadastrados na base de dados?
# delivery_people_unique = df['Delivery_person_ID'].nunique()
# print(delivery_people_unique)

# 3. Qual a média de idade dos entregadores por cidade?
# print('Média agrupada por cidade\n',df.groupby('City')['Delivery_person_Age'].mean(),'\n')

# 4. Qual a mediana de idade dos entregadores por cidade?
# print('Mediana agrupada por cidade\n',df.groupby('City')['Delivery_person_Age'].median(),'\n')

# 5. Qual o número total de entregas feitas por densidade de tráfego?
# print('Quantidade de entregas realizadas por densidade de tráfego\n',df.groupby('Road_traffic_density')['ID'].count())

# 6. Qual a média das avaliações das entregas feitas por densidade de tráfego?
# print('Média de avaliações agrupada por densidade de tráfego\n',df.groupby('Road_traffic_density')['Delivery_person_Ratings'].mean())

# 7. Qual a quantidade de entregas feitas por cidade?
# print('Quantidade de entregas feitas por cidade\n',df.groupby('City')['ID'].count())

# 8. Qual a quantidade das entregas feitas por cidade e por tipo de veículo?
# print('Média de entregas feitas por cidade e tipo de veículo:')
# print(df.groupby(['City','Type_of_vehicle'])['ID'].count())

# 9. Qual o pedido mais antigo por cada cidade?
# print('Primeira data de entrega de cada cidade')
# print( df.groupby('City')['Order_Date'].min())

# 10. Qual a última data de entrega por cada cidade?
# print('Última data de entrega de cada cidade')
# print( df.groupby('City')['Order_Date'].max())

# 11. Qual a média de avaliações das entregas feitas por condições climáticas?
# print('Média das avaliações por condições climáticas')
# print(df.groupby('Weatherconditions')['Delivery_person_Ratings'].mean())

# 12. Qual o valor da avaliação mais baixa feita por tipo de condição climática e por densidade de tráfego?
# print('Menor avaliação por condição climática e densidade de tráfego')
# print(df.groupby(['Weatherconditions','Road_traffic_density'])['Delivery_person_Ratings'].min())

# 13. Quantas entregas foram feitas no Festival?
# festival_yes_count = df[df['Festival'] == 'Yes'].shape[0]
# print(f'Quantidade de entregas feitas no festival: {festival_count}')

# 14. Qual a avaliação média das entregas feitas no Festival?
# media_avaliacoes_festival_yes = df[df['Festival'] == 'Yes']['Delivery_person_Ratings'].mean()
# print(df[df['Festival'] == 'Yes']['Delivery_person_Ratings'])
# print(f'Média de avaliações das entregas feitas no festival: {media_avaliacoes_festival_yes:.2f}')

# 15.
# menor_avaliacao_por_cidade = df[df['Festival'] == 'Yes'].groupby('City')['Delivery_person_Ratings'].min()
# print(f'Menor avaliação por cidade: {menor_avaliacao_por_cidade:}')

# 16. Qual a maior avaliação feita por tipo de pedido?
# maior_avaliacao_por_tipo_pedido = df.groupby('Type_of_order')['Delivery_person_Ratings'].max()
# print(f'Maior avaliação por tipo de pedido:\n{maior_avaliacao_por_tipo_pedido}')

# 17. Qual a idade do entregador mais velho da planilha de dados?
# idade_entregador_mais_velho = df['Delivery_person_Age'].max()
# print(f'Idade do entregador mais velho: {idade_entregador_mais_velho}')

# 18. Qual a idade do entregador mais novo da planilha de dados?
# idade_entregador_mais_novo = df['Delivery_person_Age'].min()
# print(f'Idade do entregador mais velho: {idade_entregador_mais_velho}')

# 19. Quantas entregas foram feitas em cada condição climática?
# qtd_entregas_por_condicao_climatica = df.groupby('Weatherconditions')['ID'].count()
# print(f'Quantidade de entregas feitas em cada condição climática:\n{qtd_entregas_por_condicao_climatica}')

# 20.
# qtd_entregas_por_tipo_densidade_transito = df.groupby('Road_traffic_density')['ID'].count()
# print(f'Quantidade de entregas feitas por tipo de densidade de tráfego:\n{qtd_entregas_por_tipo_densidade_transito}')